version: '3.3'

services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: "ParkPals"
      POSTGRES_PASSWORD: "ParkPals"
      POSTGRES_DB: "parking_lots"
  web:
    image: parkpal-backend_web:latest
    ports:
      - 80:5000
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: "host=db;port=5432;database.py=users;username=ParkPals;password=ParkPals"
  cron:
    image: parkpal-backend_cron:latest
    depends_on:
      - db
    environment:
        DB_CONNECTION_STRING: "host=db;port=5432;database.py=users;username=ParkPals;password=ParkPals"
