version: '3.3'

services:
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: parkpal
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: carparks
  web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    command: /wait-for-it.sh db:5432 -- flask run --host=0.0.0.0
    ports:
      - 80:5000
    volumes:
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - db

  cron:
    build:
      context: ./
      dockerfile: docker/cron/Dockerfile
    command: /wait-for-it.sh db:5432 -- ./cron_start.sh
    environment:
      GOOGLE_GEOCODING_API_KEY: ${GOOGLE_GEOCODING_API_KEY}
      URA_API_ACCESS_KEY: ${URA_API_ACCESS_KEY}
      LTA_API_ACCESS_KEY: ${LTA_API_ACCESS_KEY}
      QUERY_LIMIT: ${QUERY_LIMIT}
      CRON_FREQUENCY: ${CRON_FREQUENCY}
    volumes:
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - db
