version: '3.3'

services:
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: parkpal
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: carparks
  web:
    build:
      context: ./
      dockerfile: ./main-api/Dockerfile
    ports:
      - 80:5000
    depends_on:
      - db

  cron:
    build:
      context: ./
      dockerfile: ./cron/Dockerfile
    depends_on:
      - db
